[tool.poetry]
name = "tomodachi"
version = "0.1.0"
description = "Multipurpose Discord bot written in Python"
authors = ["howaitoreivun <72914371+howaitoreivun@users.noreply.github.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = "^3.9"
asyncpg = "^0.22.0"
aioredis = "^1.3.1"
"discord.py" = {git = "https://github.com/Rapptz/discord.py", rev = "master"}
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
jishaku = {git = "https://github.com/Gorialis/jishaku", rev = "master"}
ujson = "^4.0.2"
discord-flags = "^2.1.1"
gTTS = "^2.2.2"
Pillow = "^8.1.2"
more-itertools = "^8.7.0"
fastapi = "^0.63.0"
uvicorn = "^0.13.4"
pydantic = "^1.8.1"
no-blocking-io = "^0.0.3"
idna = {version = "^3.1", optional = true}
urllib3 = "^1.26.4"


[tool.poetry.dev-dependencies]
black = "^20.8b1"

[tool.poetry.extras]
speed = ["uvloop"]
pgsql = ["psycopg2"]

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
